theme = {
    "accent": "rgb(139, 158, 255)",
    "accent_positive": "#33ffe6",
    "accent_negative": "#ff2c6d",
    "background_content": "white",
    "background_page": "rgb(247, 247, 247)",
    "body_text": "rgb(34, 45, 69)",
    "border": "rgb(239, 239, 239)",
    "border_style": {
        "name": "underlined",
        "borderWidth": "0px 0px 1px 0px",
        "borderStyle": "solid",
        "borderRadius": 0,
    },
    "button_border": {"width": "1px", "color": "rgb(34, 45, 69)", "radius": "0px"},
    "button_capitalization": "uppercase",
    "button_text": "rgb(34, 45, 69)",
    "button_background_color": "rgb(239, 239, 239)",
    "control_border": {"width": "1px", "color": "rgb(163, 164, 166)", "radius": "0px"},
    "control_background_color": "white",
    "control_text": "rgb(64, 64, 64)",
    "card_margin": "15px",
    "card_padding": "5px",
    "card_border": {
        "width": "1px",
        "style": "solid",
        "color": "rgb(239, 239, 239)",
        "radius": "2px",
    },
    "card_background_color": "white",
    "card_box_shadow": "0px 0px 0px rgba(0,0,0,0)",
    "card_outline": {"width": "0px", "style": "solid", "color": "#c8c8c8"},
    "card_header_margin": "0px",
    "card_header_padding": "0px",
    "card_header_border": {
        "width": "0px",
        "style": "solid",
        "color": "#c8c8c8",
        "radius": "0px",
    },
    "card_header_background_color": "white",
    "card_header_box_shadow": "0px 0px 0px rgba(0,0,0,0)",
    "breakpoint_font": "1200px",
    "breakpoint_stack_blocks": "700px",
    "colorway": [
        "#3366CC",
        "#DC3912",
        "#FF9900",
        "#109618",
        "#990099",
        "#0099C6",
        "#DD4477",
        "#66AA00",
    ],
    "colorscale": [
        "#0d0887",
        "#46039f",
        "#7201a8",
        "#9c179e",
        "#bd3786",
        "#d8576b",
        "#ed7953",
        "#fb9f3a",
        "#fdca26",
        "#f0f921",
    ],
    "dbc_primary": "#ffd347",
    "dbc_secondary": "#babbc0",
    "dbc_info": "#009AC7",
    "dbc_gray": "#adb5bd",
    "dbc_success": "#33ffe6",
    "dbc_warning": "#F9F871",
    "dbc_danger": "#ff2c6d",
    "font_family": "Open Sans",
    "font_family_header": "Open Sans",
    "font_family_headings": "Open Sans",
    "font_size": "17px",
    "font_size_smaller_screen": "15px",
    "font_size_header": "24px",
    "title_capitalization": "none",
    "header_content_alignment": "spread",
    "header_margin": "0px 0px 15px 0px",
    "header_padding": "0px",
    "header_border": {
        "width": "0px",
        "style": "solid",
        "color": "#c8c8c8",
        "radius": "0px",
    },
    "header_background_color": "white",
    "header_box_shadow": "none",
    "header_text": "rgb(34, 45, 69)",
    "heading_text": "rgb(34, 45, 69)",
    "text": "rgb(34, 45, 69)",
    "report_background_content": "#FAFBFC",
    "report_background_page": "white",
    "report_text": "black",
    "report_font_family": "Computer Modern",
    "report_font_size": "12px",
    "font_headings_size": None,
}
